# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf26c8b920e5a282a14e1faabab5f225625e98076cda7be456ff0f370a55011be3de21875cd01452c0df02356ff27fd84b28ac5a565db1d6ae062abf65e8f71

test:
  secret_key_base: a1eea9accebffa670e149a2d0d5df7db98d6b904830c5f5240ba302ee0bf5286f3d28058243d0cb9048787eee449a1d1da566dc6254608f27948de6143b79366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
