# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83bc5deb9f3b97809caa069a95542d4780751c5fb0793e5bcb3692d0c773d65321816cf7c32a0f4d0e7a1f60f4dd2e0c1a50a468ded14cba68297ea60c8bec79

test:
  secret_key_base: f52cba8c5aba71634edc951a743e8d071f265c67247b9cad5390e386048dafe549ed57c1fddda56e5dffce3dd47c39328a431097dd80090f12d141b04a4e6687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
