# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1908d4cefb5d0a6f35ade45d057dc3850e3c23cf4796ea451d52992dcf724bf721118cbd8ae11b9dbe728387dbc9aa5ef010dec05f6630e8d1aa69efc1bb6902

test:
  secret_key_base: 1dcb4ec141da13c0ce3623f835b3ae3dedb99be208c4677eef2764bcaf7bbbc2050fab65440840bfbb86d611b4080046020dcb797a5aa7ac114a18a0c22cf19c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
